# Configuración de conexión
#spring.datasource.url=jdbc:postgresql://localhost:5432/RentAltoke?connectTimeout=10&sslmode=prefer
#spring.datasource.username=Alex
#spring.datasource.password=xxxxxxx
#spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/RentAltoke}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:Alex}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:tu_password_real}
# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
server.port=8081